#!/usr/bin/env bash

function sync_milesrc() {
    sync_milesrc_cleanup() {
        unset args host skip_plugs sync_tmux sync_vim
        unset -f sync_milesrc_cleanup
        unset -f sync_milesrc_usage
    }

    sync_milesrc_usage() {
        echo "Usage: sync_milesrc [OPTIONS] <host1>...[hostN]"
        echo
        echo "Sync the milesrc to other hosts"
        echo
        echo "Options:"
        echo "    -h, --help      Display this help message"
        echo "    --skip-plugs    Skip plugs directory when syncing"
        echo "                    vim configs"
        echo "    -t, --tmux      Also sync tmux configs"
        echo "    -v, --vim       Also sync vim configs"
        echo
        sync_milesrc_cleanup
    }

    declare -a args
    unset skip_plug skip_plugs
    sync_tmux="tmux"
    sync_vim="vim"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            "--") shift && args+=("$@") && break ;;
            "-h"|"--help") sync_milesrc_usage; return 0 ;;
            "--skip-plugs")
                skip_plug="plug.vim"
                skip_plugs="plugs"
                ;;
            "-t"|"--tmux") unset sync_tmux ;;
            "-v"|"--vim") unset sync_vim ;;
            *) args+=("$1") ;;
        esac
        shift
    done
    [[ -z ${args[@]} ]] || set -- "${args[@]}"

    [[ $# -eq 0 ]] && sync_milesrc_usage && return 1

    for host in "$@"; do
        rsync -c --delete --exclude .git \
            --exclude ${skip_plug:-IGNORE_THIS} \
            --exclude ${skip_plugs:-IGNORE_THIS} \
            --exclude ${sync_tmux:-IGNORE_THIS} \
            --exclude ${sync_vim:-IGNORE_THIS} \
            -lrtv ~/.milesrc/ $host:.milesrc
    done

    sync_milesrc_cleanup
}

if [[ -n ${BASH_SOURCE[0]} ]]; then
    case "$0" in
        *"bash") ;;
        *) sync_milesrc "$@" ;;
    esac
fi
