#!/usr/bin/env bash
# A script for syncing the milesrc to other hosts.
# by Miles Whittaker <mjwhitta@gmail.com>
#
# --------------------------------------------------------------------
# The MIT License (MIT)
#
# Copyright (c) 2018 Miles Whittaker
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# --------------------------------------------------------------------

function sync_milesrc() {
    if [[ -z $(command -v rsync) ]]; then
        echo "rsync is not installed"
        return 2
    fi

    sync_milesrc_cleanup() {
        unset args host skip_plugs sync_tmux sync_vim
        unset -f sync_milesrc_cleanup sync_milesrc_usage
    }

    sync_milesrc_usage() {
        echo "Usage: sync_milesrc [OPTIONS] <host1>...[hostN]"
        echo
        echo "Sync the milesrc to other hosts"
        echo
        echo "Options:"
        echo "    -h, --help      Display this help message"
        echo "    --skip-plugs    Skip plugs directory when syncing"
        echo "                    vim configs"
        echo "    -t, --tmux      Also sync tmux configs"
        echo "    -v, --vim       Also sync vim configs"
        echo
        sync_milesrc_cleanup
    }

    declare -a args
    unset skip_plug skip_plugs
    sync_tmux="tmux"
    sync_vim="vim"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            "--") shift && args+=("$@") && break ;;
            "-h"|"--help") sync_milesrc_usage; return 0 ;;
            "--skip-plugs")
                skip_plug="plug.vim"
                skip_plugs="plugs"
                ;;
            "-t"|"--tmux") unset sync_tmux ;;
            "-v"|"--vim") unset sync_vim ;;
            *) args+=("$1") ;;
        esac
        shift
    done
    [[ -z ${args[@]} ]] || set -- "${args[@]}"

    [[ $# -eq 0 ]] && sync_milesrc_usage && return 1

    for host in "$@"; do
        rsync -c --delete --exclude .git \
            --exclude ${skip_plug:-IGNORE_THIS} \
            --exclude ${skip_plugs:-IGNORE_THIS} \
            --exclude ${sync_tmux:-IGNORE_THIS} \
            --exclude ${sync_vim:-IGNORE_THIS} \
            -lrtv ~/.milesrc/ $host:.milesrc
    done

    sync_milesrc_cleanup
}

if [[ -n ${BASH_SOURCE[0]} ]]; then
    case "$0" in
        *"bash") ;;
        *) sync_milesrc "$@" ;;
    esac
fi
